version: 2.1

# orbs:
#   terraform: circleci/terraform@1.3.1
  
executors:
  build-image:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:0.13.0

commands:
  init_script:
    steps:
      - run:
          name: Authenticate to Google
          command: |
            echo $GCLOUD_SERVICE_KEY | base64 -d > /tmp/gcloud-service-key.json

jobs:
  plan:
    executor: build-image
    steps:
      - checkout
      - init_script
      - run:
          name: terraform plan
          command: |
            cd terraform
            terraform init -input=false
            terraform plan -out tfapply -var-file terraform.tfvars
      - persist_to_workspace:
          root: terraform
          paths:
            - echo-output

  apply:
    executor: build-image
    steps:
      - checkout
      - init_script
      - attach_workspace:
          at: terraform
      - run:
          name: terraform apply
          command: |
            terraform apply -auto-approve tfapply


# workflows:
#   terraform_flow:
#     jobs:
#       - plan
#       - hold:
#           type: approval
#           requires:
#             - plan
#           filters:
#             branches:
#               ignore: master
#       - apply:
#           requires:
#             - hold
#           filters:
#             branches:
#               ignore: master


workflows:
  version: 2
  plan_approve_apply:
    jobs:
      - plan
      - hold-apply:
          type: approval
          requires:
            - plan
      - apply:
          requires:
            - hold-apply
